[package]
name = "silex-zed"
version = "0.18.0"
edition = "2021"
authors = ["Matanek"]
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/Matanek/Silex-Extension-Zed"

[lib]
crate-type = ["cdylib"]
path = "Extension/Sources/lib.rs"

[dependencies]
zed_extension_api = "=0.3.0"
