id = "silex"
name = "Silex"
version = "0.51.0"
schema_version = 1
authors = ["Matanek"]
description = "Silex language support"
repository = "https://github.com/Matanek/Silex-Extension-Zed"
languages = ["languages/silex"]

[language_servers.silex]
name = "Silex LSP"
languages = ["Silex"]

[grammars.silex]
repository = "https://github.com/Matanek/Silex-Extension-Zed"
rev = "402ca62ea354c4a8ae7bf32f8d24420fc15a8d60"
