id = "silex"
name = "Silex"
version = "0.50.0"
schema_version = 1
authors = ["Matanek"]
description = "Silex language support"
repository = "https://github.com/Matanek/Silex-Extension-Zed"
languages = ["languages/silex"]

[language_servers.silex]
name = "Silex LSP"
languages = ["Silex"]

[grammars.silex]
repository = "https://github.com/Matanek/Silex-Extension-Zed"
rev = "6073fb728817d1d3d2493ba2ef4780666b7f8eca"
