id = "silex"
name = "Silex"
version = "0.42.0"
schema_version = 1
authors = ["Matanek"]
description = "Silex language support"
repository = "https://github.com/Matanek/Silex-Extension-Zed"
languages = ["languages/silex"]

[language_servers.silex]
name = "Silex LSP"
languages = ["Silex"]

[grammars.silex]
repository = "https://github.com/Matanek/Silex-Extension-Zed"
rev = "1de9732bc149ee9c712eec7ef58db4d39e6d66e3"
